name: flutter_blocknote_editor
description: 'A Flutter package (beta) that embeds BlockNoteJS inside a WebView with bidirectional communication, transaction batching, and undo/redo safety.'
version: 0.0.2
homepage: https://github.com/NarekManukyan/flutter_blocknote_editor
repository: https://github.com/NarekManukyan/flutter_blocknote_editor
issue_tracker: https://github.com/NarekManukyan/flutter_blocknote_editor/issues

topics:
  - flutter
  - blocknote
  - editor
  - rich-text
  - webview
  - text-editor
  - markdown
  - wysiwyg
  - block-editor
  - mobile

environment:
  sdk: ^3.10.7
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  flutter_svg: ^2.0.10+1
  json_annotation: ^4.9.0
  shelf: ^1.4.2
  shelf_static: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/web/
    - assets/icons/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
